### ISSUE TITLE
i am  ai cs6,buy not save as

### ISSUE THREAD

**Issue by falali009** [creold/ai-to-psd#3]

**Comment by falali009** [comment]
some layer no path    ， is it  too many group？

**Comment by creold** [comment]
Hi @falali009 . Can you attach in message a screenshot of the Illustrator layer with objects and describe the problem in some detail?

**Comment by falali009** [comment]
[http://ad.wondersea.mobi/h5/cs/ai.png](http://ad.wondersea.mobi/h5/cs/ai.png)
[http://ad.wondersea.mobi/h5/cs/ai.png](http://ad.wondersea.mobi/h5/cs/ps.png)

**Comment by falali009** [comment]
this two link is temp link .. so...  ..

**Comment by creold** [comment]
![temp](https://user-images.githubusercontent.com/32217031/55381604-f64ab280-553c-11e9-85af-1436281624dc.jpg)
Maybe this object has a stroke or unclosed path? Paths with stroke, gradients, meshes rasterized when exporting. Or attach .AI file here.
